#!/bin/bash

# First step is to determine whether the system is on Graham or not
# Check current path

GRAHAM_REPO=/scratch/tkai/scwg2018_python_neuroimaging/

#If Scinet then enter first name to create Repo
if [ -d "$GRAHAM_REPO" ]; then

        echo "Please enter your first name (no spaces or special characters!)"
        read first_name
        mkdir -p /scratch/$USER/$first_name/
        git clone https://github.com/kaitj/scwg2018_python_neuroimaging /scratch/$USER/$first_name
        cd /scratch/$USER/$first_name/
	    git checkout khanlab_tutorial
        rm -rf "/scratch/$USER/$first_name/data"
        ln -s $GRAHAM_REPO/data /scratch/$USER/$first_name/data

        echo "Workshop at /scratch/$USER/$first_name/"

#Otherwise we use a Binder instance
else

        echo "Assuming that you're using a Binder instance, downloading data!"

        # download T1w scans
        cat download_list | \
          xargs -I '{}' aws s3 sync --no-sign-request \
          s3://openneuro/ds000030/ds000030_R1.0.5/uncompressed/{}/anat \
          ./data/ds000030/{}/anat

        # download resting state fMRI scans
        cat download_list | \
          xargs -I '{}' aws s3 sync --no-sign-request \
          s3://openneuro/ds000030/ds000030_R1.0.5/uncompressed/{}/func \
          ./data/ds000030/{}/func \
          --exclude '*' \
          --include '*task-rest_bold*'

        # download fmriprep preprocessed anat data
        cat download_list | \
          xargs -I '{}' aws s3 sync --no-sign-request \
          s3://openneuro/ds000030/ds000030_R1.0.5/uncompressed/derivatives/fmriprep/{}/anat \
          ./data/ds000030/derivatives/fmriprep/{}/anat

        # download fmriprep preprocessed func data
        cat download_list | \
          xargs -I '{}' aws s3 sync --no-sign-request \
          s3://openneuro/ds000030/ds000030_R1.0.5/uncompressed/derivatives/fmriprep/{}/func \
          ./data/ds000030/derivatives/fmriprep/{}/func \
          --exclude '*' \
          --include '*task-rest_bold*'


fi
